config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'orders/index'
  get 'simple_pages/thank_you'
  get 'simple_pages/about'
  get 'simple_pages/landing_page'
  get 'simple_pages/index'
  get 'simple_pages/contact'
  post 'simple_pages/thank_you'
  post 'payments/create'
  root 'simple_pages#index'
  
  mount ActionCable.server => '/cable'
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :product
    belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user!
    def index
        @orders = Order.includes(:product).all
    end
    
    def show
        
    end
    
    def new
    end

    def create
    end

    def destroy
    end

end

app/views/orders/index.html.erb
<div class="container">
  <h1>Orders</h1>
  <div class="row">
    <% @orders.each do |order| %>
    <div class="col-sm-6 col-md-4">
      <h2>
      <%= link_to "Order: " + order.id.to_s, order %>:
      <%= link_to order.product.name, order.product %>
      </h2>
      <p><%= order.product.description %></p>
      <strong>$ <%= order.product.price %></strong>
    </div>
    <% end %>
  </div>
  <%= link_to 'Back', simple_pages_landing_page_url %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h1>Order details</h1>
  <p>
    <strong>Order #:</strong>
    <%= @order.id %>
  </p>
  <p>
    <strong>User ID:</strong>
    <%= @order.user_id %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @order.product.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @order.product.description %>
  </p>
  <p>
    <strong>Colour:</strong>
    <%= @order.product.colour %>
  </p>
  <p>
    <strong>Total:</strong>
    <%= number_to_currency(@order.total) %>
  </p>
  <%= image_tag(@order.product.image_url, class: "img-responsive product-image") %>
  <%= link_to 'Back', orders_path %>
</div>