config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'orders/index'
  get 'simple_pages/thank_you'
  get 'simple_pages/about'
  get 'simple_pages/landing_page'
  get 'simple_pages/index'
  get 'simple_pages/contact'
  post 'simple_pages/thank_you'
  post 'payments/create'
  root 'simple_pages#index'
  
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheeeeeese</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <nav class="bar white padding card-2 top">
      <h3 class="left">We Love Cheese!</h3>
      <ul class="right">
        <li class="bar-item button"><%= link_to "Home", simple_pages_index_path %></li>
        <li class="bar-item button"><%= link_to "Products", products_path %></li>
        <li class="bar-item button"><%= link_to "About", simple_pages_about_path %></li>
        <li class="bar-item button">
          <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          <% else %>
          <%= link_to('Login', new_user_session_path) %>
          <% end %>
        </li>
      </ul>
    </nav>
    <div class="container panel">
      <% if notice %>
      <p id="notice" class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p id="alert" class="alert alert-warning"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <footer class="center light-grey padding-32">
      <h5> &copy; We Love Cheese </h5>
    </footer>
  </body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheeeeeese</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <nav class="bar white padding card-2 top">
    <h3 class="left">We Love Cheese!</h3>
    <ul class="right">
      <li class="bar-item button"><%= link_to "Home", simple_pages_index_path %></li>
      <li class="bar-item button"><%= link_to "Products", products_path %></li>
      <li class="bar-item button"><%= link_to "About", simple_pages_about_path %></li>
      <li class="bar-item button"><%= link_to "Contact", simple_pages_contact_path %></li>
      <li class="bar-item button">
        <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
        <%= link_to('Login', new_user_session_path) %>
        <% end %>
      </li>
      <li class="bar-item button"><%= form_with(url: products_path, method: 'get', local: true) do |form| %>
        <!-- <%= form.label :q, 'Search for:' %> no need for search label when the placeholder and button are marked so the user knows what to do -->
        <%= form.text_field :q, id: 'q', value: params[:q] %>
        <%= form.submit 'Search', class:'btn' %>
      <% end %></li>
    </ul>
  </nav>
  <div class="container panel">
    <%= yield %>
  </div>
  <footer class="center light-grey padding-32">
    <h5> &copy; We Love Cheese </h5>
  </footer>
</html>